import type { Opportunity, ServiceOption } from './types'

export const serviceOptions: ServiceOption[] = [
  { key: 'automation', name: 'Process automation', shortName: 'Automation' },
  { key: 'cybersecurity', name: 'Cybersecurity', shortName: 'Security' },
  {
    key: 'software-development',
    name: 'Software development',
    shortName: 'Software',
  },
]

export const opportunityFixtures: Opportunity[] = [
  {
    id: 'op-lufthansa-automation',
    companyId: 'company-lufthansa',
    companyName: 'Lufthansa Group',
    domain: 'lufthansagroup.com',
    industry: 'Aviation',
    geography: 'Germany',
    service: 'automation',
    status: 'new',
    eligibility: 'eligible',
    score: 86,
    coverage: 0.88,
    strongestSignal: 'Group-wide efficiency program',
    signalCount: 5,
    lastResearchedAt: '2026-09-25T14:42:00Z',
  },
  {
    id: 'op-dhl-automation',
    companyId: 'company-dhl',
    companyName: 'DHL Group',
    domain: 'group.dhl.com',
    industry: 'Logistics',
    geography: 'Germany',
    service: 'automation',
    status: 'shortlisted',
    eligibility: 'eligible',
    score: 81,
    coverage: 0.94,
    strongestSignal: 'Agentic AI adoption program',
    signalCount: 6,
    lastResearchedAt: '2026-09-25T14:35:00Z',
  },
  {
    id: 'op-nordic-freight-automation',
    companyId: 'company-nordic-freight',
    companyName: 'Nordic Freight Systems',
    domain: 'example.org',
    industry: 'Logistics',
    geography: 'Sweden',
    service: 'automation',
    status: 'new',
    eligibility: 'needs_research',
    score: 64,
    coverage: 0.42,
    strongestSignal: 'Shared-service consolidation',
    signalCount: 2,
    lastResearchedAt: '2026-09-25T13:18:00Z',
  },
  {
    id: 'op-alpine-bank-security',
    companyId: 'company-alpine-bank',
    companyName: 'Alpine Commercial Bank',
    domain: 'example.com',
    industry: 'Financial services',
    geography: 'Austria',
    service: 'cybersecurity',
    status: 'new',
    eligibility: 'eligible',
    score: 79,
    coverage: 0.78,
    strongestSignal: 'Cloud security modernization',
    signalCount: 4,
    lastResearchedAt: '2026-09-25T12:55:00Z',
  },
  {
    id: 'op-baltic-retail-software',
    companyId: 'company-baltic-retail',
    companyName: 'Baltic Retail Cooperative',
    domain: 'example.net',
    industry: 'Retail',
    geography: 'Lithuania',
    service: 'software-development',
    status: 'new',
    eligibility: 'eligible',
    score: 73,
    coverage: 0.7,
    strongestSignal: 'Digital commerce expansion',
    signalCount: 3,
    lastResearchedAt: '2026-09-25T11:24:00Z',
  },
]

