import { apiRequest } from './client'
import type { OpportunityStatus } from './opportunities'

export interface Translation { id: string; target_language: 'en' | 'ro'; translated_excerpt: string; provider_model: string; source_text_hash: string; created_at: string }
export interface Source { id: string; canonical_url: string; source_type: string; title: string; retrieved_at: string; publication_date: string | null; event_date: string | null; content_hash: string }
export interface Evidence { id: string; source_id: string; excerpt: string; start_offset: number; end_offset: number; factual_claim: string; event_group_key: string; source: Source; translations: Translation[] }
export interface CompanyResult { id: string; canonical_domain: string; display_name: string; aliases: string[]; facts: Record<string, unknown>; assessments: Array<{ id: string; profile_version_id: string; signal_id: string; status: string; evidence_strength: string | null; rationale: string; evidence: Evidence[]; model_version: string; prompt_version: string }>; scores: Array<{ id: string; profile_version_id: string; calculation_version: string; score: number; eligibility: string; coverage: number; icp_fit: number; positive_strength: number; penalty_points: number; contributions: Array<Record<string, unknown>>; exclusion_reasons: string[]; warnings: string[]; created_at: string }>; research_history: Array<{ id: string; profile_version_id: string; status: string; progress: Array<Record<string, unknown>>; partial_errors: Array<Record<string, unknown>>; usage: Record<string, unknown>; queued_at: string; started_at: string | null; finished_at: string | null }>; created_at: string; updated_at: string }
export const getCompanyResult = (id: string, signal?: AbortSignal) => apiRequest<CompanyResult>(`/companies/${encodeURIComponent(id)}`, { signal })
export type { OpportunityStatus }
