import { useEffect, useMemo, useState } from 'react'

import { getProfile, saveProfile } from './repository'
import type { ProfileDraft, SignalDraft, SignalEffect } from './types'

const steps = ['Your service', 'Ideal customer', 'Buying signals', 'Negative signals', 'Review']
const importance = [{ label: 'High', value: 20 }, { label: 'Medium', value: 10 }, { label: 'Low', value: 5 }]
const ages = [{ label: 'Very recent', value: 180 }, { label: 'Recent', value: 365 }, { label: 'Established', value: 730 }]
const input = 'mt-2 w-full rounded-lg border border-[#8E867C] bg-white px-3.5 py-3 text-sm text-[#20242A] outline-none placeholder:text-[#6F6A64] focus:border-[#C94F12] focus:ring-2 focus:ring-[#C94F12]/20'

function Field({ label, help, value, onChange, multiline = false, placeholder }: { label: string; help: string; value: string; onChange: (value: string) => void; multiline?: boolean; placeholder?: string }) {
  return <label className="block text-sm font-semibold text-[#353A40]">{label}<span className="mt-1 block text-xs font-normal leading-5 text-[#73706A]">{help}</span>{multiline ? <textarea className={`${input} min-h-28 resize-y`} placeholder={placeholder} value={value} onChange={(event) => onChange(event.target.value)} /> : <input className={input} placeholder={placeholder} value={value} onChange={(event) => onChange(event.target.value)} />}</label>
}

function SignalCard({ signal, index, onChange, onRemove, negative }: { signal: SignalDraft; index: number; onChange: (signal: SignalDraft) => void; onRemove: () => void; negative?: boolean }) {
  return <article className="rounded-xl border border-[#DED9D1] bg-white p-5 shadow-sm">
    <div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-[#B64B16]">{negative ? `Rule ${index + 1}` : `Buying signal ${index + 1}`}</p><p className="mt-1 text-xs text-[#68645F]">This only affects a company when public evidence supports it.</p></div><button className="text-xs font-semibold text-[#8A4030]" onClick={onRemove}>Remove</button></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><Field help={negative ? 'What condition should lower priority or exclude a company?' : 'What business question should research answer?'} label="Research question" multiline placeholder="Has the company announced an operational-efficiency programme?" value={signal.question} onChange={(question) => onChange({ ...signal, question })} /><Field help="Describe the specific facts that count as evidence." label="Evidence that counts" multiline placeholder="A named initiative with a recent date and clear operational scope." value={signal.positiveCriteria} onChange={(positiveCriteria) => onChange({ ...signal, positiveCriteria })} /></div>
    <div className="mt-5 grid gap-5 md:grid-cols-3">{negative && <label className="text-sm font-semibold text-[#353A40]">Consequence<span className="mt-1 block text-xs font-normal text-[#73706A]">Warning or firm exclusion.</span><select className={input} value={signal.effect} onChange={(event) => onChange({ ...signal, effect: event.target.value as SignalEffect })}><option value="penalty">Lower priority</option><option value="disqualifier">Exclude company</option></select></label>}<label className="text-sm font-semibold text-[#353A40]">Importance<span className="mt-1 block text-xs font-normal text-[#73706A]">Scoring stays internal.</span><select className={input} value={signal.weight >= 15 ? 20 : signal.weight >= 8 ? 10 : 5} onChange={(event) => onChange({ ...signal, weight: Number(event.target.value) })}>{importance.map((item) => <option key={item.label} value={item.value}>{item.label}</option>)}</select></label><label className="text-sm font-semibold text-[#353A40]">Evidence age<span className="mt-1 block text-xs font-normal text-[#73706A]">Older evidence is treated cautiously.</span><select className={input} value={signal.freshnessWindowDays <= 180 ? 180 : signal.freshnessWindowDays <= 365 ? 365 : 730} onChange={(event) => onChange({ ...signal, freshnessWindowDays: Number(event.target.value) })}>{ages.map((item) => <option key={item.label} value={item.value}>{item.label}</option>)}</select></label></div>
  </article>
}

function Review({ profile }: { profile: ProfileDraft }) {
  const positives = profile.signals.filter((item) => item.effect === 'positive'); const negatives = profile.signals.filter((item) => item.effect !== 'positive')
  return <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-[#DED9D1] bg-white p-5"><h3 className="font-semibold">Service and ideal customer</h3><dl className="mt-4 space-y-4 text-sm">{[['Service', profile.name], ['Description', profile.description], ['Industries', profile.industries || 'Not restricted'], ['Markets and geography', profile.geographies || 'Not restricted'], ['Company size', profile.companySize || 'Not restricted']].map(([label, value]) => <div key={label}><dt className="text-xs font-semibold uppercase tracking-wide text-[#68645F]">{label}</dt><dd className="mt-1 leading-6 text-[#4F545A]">{value || 'Not provided'}</dd></div>)}</dl></section><section className="rounded-xl border border-[#DED9D1] bg-white p-5"><h3 className="font-semibold">Research rules</h3><p className="mt-4 text-xs font-semibold uppercase tracking-wide text-[#68645F]">Buying signals</p>{positives.map((item) => <p className="mt-2 text-sm" key={item.id}>{item.question || 'Incomplete question'} · <span className="text-[#A44818]">{importance.find((level) => level.value === item.weight)?.label ?? 'Medium'}</span></p>)}<p className="mt-5 text-xs font-semibold uppercase tracking-wide text-[#68645F]">Negative rules</p>{negatives.length ? negatives.map((item) => <p className="mt-2 text-sm" key={item.id}>{item.question || 'Incomplete rule'} · <span className="text-[#A44818]">{item.effect === 'disqualifier' ? 'Exclude' : 'Lower priority'}</span></p>) : <p className="mt-2 text-sm text-[#68645F]">None added</p>}</section></div>
}

export function ProfileWorkspace() {
  const [profile, setProfile] = useState<ProfileDraft | null>(null); const [step, setStep] = useState(0); const [state, setState] = useState<'loading' | 'ready' | 'saving' | 'saved' | 'error'>('loading')
  useEffect(() => { void getProfile().then((value) => { setProfile(value); setState('ready') }).catch(() => setState('error')) }, [])
  const groups = useMemo(() => ({ buying: profile?.signals.filter((item) => item.effect === 'positive') ?? [], negative: profile?.signals.filter((item) => item.effect !== 'positive') ?? [] }), [profile])
  if (state === 'loading') return <div className="rounded-xl border border-[#DED9D1] bg-white p-10 text-[#73706A]">Loading service profile…</div>
  if (!profile || state === 'error') return <div className="rounded-xl border border-[#E6B8AE] bg-[#FFF4F1] p-10 text-[#8A2F20]">The service profile could not be loaded.</div>
  const replace = (next: SignalDraft) => setProfile({ ...profile, signals: profile.signals.map((item) => item.id === next.id ? next : item) }); const remove = (id: string) => setProfile({ ...profile, signals: profile.signals.filter((item) => item.id !== id) })
  const add = (effect: SignalEffect) => setProfile({ ...profile, signals: [...profile.signals, { id: crypto.randomUUID(), question: '', positiveCriteria: '', exclusions: '', effect, weight: effect === 'positive' ? 20 : 10, freshnessWindowDays: 365 }] })
  const persist = async () => { setState('saving'); try { setProfile(await saveProfile(profile)); setState('saved') } catch { setState('error') } }
  return <div className="text-[#20242A]"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-wider text-[#A44818]">Service Profile · Version {profile.version ?? 1}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Define who your service is for</h1><p className="mt-3 text-sm leading-6 text-[#68645F]">Describe the customers you want to find and the public signals that matter. Research will use this profile consistently.</p></div>
    <ol className="mt-8 grid gap-2 md:grid-cols-5">{steps.map((label, index) => <li key={label}><button aria-current={step === index ? 'step' : undefined} className={`flex w-full items-center gap-2 rounded-lg border px-3 py-3 text-left text-xs font-semibold ${step === index ? 'border-[#E86722] bg-[#FFF1E8] text-[#9F3E0E]' : 'border-[#E2DED7] bg-white text-[#716C65]'}`} onClick={() => setStep(index)}><span className={`grid size-5 place-items-center rounded-full text-[11px] ${step === index ? 'bg-[#C94F12] text-white' : index < step ? 'bg-[#3F7054] text-white' : 'bg-[#E5E1DA]'}`}>{index < step ? '✓' : index + 1}</span>{label}</button></li>)}</ol>
    <section className="mt-6 rounded-2xl border border-[#DCD7CF] bg-[#FCFBF8] p-6 shadow-[0_8px_28px_rgba(58,45,31,0.06)] sm:p-8">
      {step === 0 && <div><h2 className="text-xl font-semibold">Your service</h2><p className="mt-2 text-sm text-[#6F6A64]">Give research business context. This is internal guidance, not marketing copy.</p><div className="mt-6 space-y-6"><Field help="Use the name your commercial team uses for this offer." label="Service name" placeholder="Process automation advisory" value={profile.name} onChange={(name) => setProfile({ ...profile, name })} /><Field help="Explain what you deliver, the problems it solves, and the expected customer outcomes." label="Service description" multiline placeholder="We help complex organisations reduce manual work and improve operational control." value={profile.description} onChange={(description) => setProfile({ ...profile, description })} /></div></div>}
      {step === 1 && <div><h2 className="text-xl font-semibold">Ideal customer</h2><p className="mt-2 text-sm text-[#6F6A64]">Leave a field blank when it should not restrict discovery.</p><div className="mt-6 grid gap-6 md:grid-cols-2"><Field help="Business sectors your team serves." label="Industries" placeholder="Logistics, manufacturing, financial services" value={profile.industries} onChange={(industries) => setProfile({ ...profile, industries })} /><Field help="Supported countries, regions, or markets." label="Markets and geography" placeholder="Central and Eastern Europe" value={profile.geographies} onChange={(geographies) => setProfile({ ...profile, geographies })} /><Field help="Describe size in normal business language." label="Company size" placeholder="Large organisations with more than one thousand employees" value={profile.companySize} onChange={(companySize) => setProfile({ ...profile, companySize })} /><Field help="Characteristics that make delivery valuable." label="Operational characteristics" placeholder="Multiple sites, shared services, regulated processes" value={profile.operationalComplexity} onChange={(operationalComplexity) => setProfile({ ...profile, operationalComplexity })} /></div></div>}
      {step === 2 && <div><div className="flex justify-between gap-4"><div><h2 className="text-xl font-semibold">Buying signals</h2><p className="mt-2 text-sm text-[#6F6A64]">Public facts that may indicate a genuine need for your service.</p></div><button className="h-fit rounded-lg bg-[#C94F12] px-4 py-2.5 text-sm font-semibold text-white" onClick={() => add('positive')}>Add buying signal</button></div><div className="mt-6 space-y-4">{groups.buying.map((item, index) => <SignalCard index={index} key={item.id} onChange={replace} onRemove={() => remove(item.id)} signal={item} />)}</div></div>}
      {step === 3 && <div><div className="flex justify-between gap-4"><div><h2 className="text-xl font-semibold">Negative signals and disqualifiers</h2><p className="mt-2 text-sm text-[#6F6A64]">Warnings lower priority. Disqualifiers exclude a company.</p></div><button className="h-fit rounded-lg border border-[#D55A1C] bg-white px-4 py-2.5 text-sm font-semibold text-[#B44712]" onClick={() => add('penalty')}>Add rule</button></div><div className="mt-6 space-y-4">{groups.negative.map((item, index) => <SignalCard index={index} key={item.id} negative onChange={replace} onRemove={() => remove(item.id)} signal={item} />)}{!groups.negative.length && <p className="rounded-xl border border-dashed border-[#CFC8BE] bg-white p-8 text-center text-sm text-[#68645F]">No negative rules added. Continue if your team does not need them.</p>}</div></div>}
      {step === 4 && <div><h2 className="text-xl font-semibold">Review and activate</h2><p className="mt-2 text-sm text-[#6F6A64]">Saving creates a new version. Previous research keeps the criteria it originally used.</p><div className="mt-6"><Review profile={profile} /></div></div>}
      <div className="mt-8 flex items-center justify-between border-t border-[#E3DED6] pt-5"><button className="rounded-lg border border-[#D5D0C8] bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-40" disabled={step === 0} onClick={() => setStep((value) => value - 1)}>Back</button><div className="flex items-center gap-3">{state === 'saved' && <span className="text-sm font-medium text-[#31704E]">Profile version saved</span>}{step < 4 ? <button className="rounded-lg bg-[#C94F12] px-5 py-2.5 text-sm font-semibold text-white" onClick={() => { setState('ready'); setStep((value) => value + 1) }}>Continue</button> : <button className="rounded-lg bg-[#C94F12] px-5 py-2.5 text-sm font-semibold text-white" disabled={state === 'saving'} onClick={() => void persist()}>{state === 'saving' ? 'Saving…' : 'Save and activate profile'}</button>}</div></div>
    </section></div>
}
