import { useEffect, useMemo, useState } from 'react'

import { errorMessage } from '../../api/errors'
import { getProfile, saveProfile } from './repository'
import type { ProfileDraft, SignalDraft, SignalEffect } from './types'

const steps = ['What we sell', 'Who we target', 'What we look for']
const importance = [{ label: 'High', value: 20 }, { label: 'Medium', value: 10 }, { label: 'Low', value: 5 }]
const ages = [{ label: 'Last 6 months', value: 180 }, { label: 'Last year', value: 365 }, { label: 'Last 2 years', value: 730 }]
const serviceOptions = [
  { name: 'RPA developers', profileName: 'RPA', title: 'RPA & automation', short: 'Automate repetitive operations and improve process accuracy.', description: 'We provide RPA development expertise to design, build, test, and maintain reliable software automations that reduce repetitive work and improve process accuracy.' },
  { name: 'Cybersecurity specialists', profileName: 'Cybersecurity', title: 'Cybersecurity', short: 'Strengthen security, resilience, and regulatory readiness.', description: 'We provide cybersecurity expertise to assess risk, strengthen security controls, improve operational resilience, and support organisations responding to regulatory and technology change.' },
  { name: 'AI specialists', profileName: 'Applied AI', title: 'Applied AI', short: 'Identify and deliver practical AI use cases.', description: 'We provide AI expertise to identify valuable use cases, design and implement responsible AI solutions, and integrate them into existing business processes and systems.' },
  { name: 'Process excellence roles', profileName: 'Process excellence', title: 'Process excellence', short: 'Redesign workflows and deliver measurable operational gains.', description: 'We provide process excellence expertise to analyse and redesign workflows, establish continuous-improvement practices, and deliver measurable gains in quality, speed, and cost.' },
]
const regions = ['Eastern Europe', 'Western Europe', 'Northern Europe', 'Southern Europe', 'Worldwide']
const industries = ['Financial services', 'Manufacturing', 'Energy & utilities', 'Retail', 'Logistics', 'Telecommunications', 'Healthcare']
const input = 'mt-2 w-full rounded-xl border border-[#CFC7BC] bg-white px-3.5 py-3 text-sm text-[#20242A] outline-none placeholder:text-[#8B857D] focus:border-[#E86722] focus:ring-2 focus:ring-[#E86722]/20'
const values = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean)
const toggleValue = (current: string, value: string) => { const selected = values(current); return (selected.includes(value) ? selected.filter((item) => item !== value) : [...selected, value]).join(', ') }

function Field({ label, help, value, onChange, multiline = false, placeholder }: { label: string; help: string; value: string; onChange: (value: string) => void; multiline?: boolean; placeholder?: string }) {
  return <label className="block text-sm font-semibold text-[#353A40]">{label}<span className="mt-1 block text-xs font-normal leading-5 text-[#73706A]">{help}</span>{multiline ? <textarea className={`${input} min-h-24 resize-y`} placeholder={placeholder} value={value} onChange={(event) => onChange(event.target.value)} /> : <input className={input} placeholder={placeholder} value={value} onChange={(event) => onChange(event.target.value)} />}</label>
}

function ChipGroup({ label, help, options, selected, onToggle }: { label: string; help: string; options: string[]; selected: string; onToggle: (value: string) => void }) {
  const current = values(selected)
  return <fieldset><legend className="text-sm font-semibold text-[#353A40]">{label}</legend><p className="mt-1 text-xs leading-5 text-[#73706A]">{help}</p><div className="mt-3 flex flex-wrap gap-2">{options.map((option) => { const active = current.includes(option); return <button aria-pressed={active} className={`rounded-full border px-3.5 py-2 text-sm font-medium transition ${active ? 'border-[#D85A17] bg-[#FFF0E6] text-[#9F3E0E]' : 'border-[#D7D1C8] bg-white text-[#625D57] hover:border-[#E86722]'}`} key={option} onClick={() => onToggle(option)} type="button">{active && <span aria-hidden="true">✓ </span>}{option}</button> })}</div></fieldset>
}

function SignalCard({ signal, index, onChange, onRemove, negative }: { signal: SignalDraft; index: number; onChange: (signal: SignalDraft) => void; onRemove: () => void; negative?: boolean }) {
  return <article className="rounded-xl border border-[#D8D1C7] bg-white p-5 shadow-sm"><div className="flex justify-between gap-4"><div><p className={`text-xs font-bold uppercase tracking-wider ${negative ? 'text-[#8B5540]' : 'text-[#B64B16]'}`}>{negative ? `Warning ${index + 1}` : `Buying signal ${index + 1}`}</p><p className="mt-1 text-xs text-[#68645F]">Only applied when public evidence supports it.</p></div><button className="text-xs font-semibold text-[#8A4030]" onClick={onRemove} type="button">Remove</button></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><Field help={negative ? 'What would make this company a weaker fit?' : 'What should research notice about this company?'} label={negative ? 'Warning condition' : 'Signal question'} multiline placeholder={negative ? 'Does the company already have a large internal automation team?' : 'Has the company announced an efficiency programme?'} value={signal.question} onChange={(question) => onChange({ ...signal, question })} /><Field help="Describe the concrete facts that count as proof." label="Evidence that counts" multiline placeholder="A named, dated initiative with clear operational scope." value={signal.positiveCriteria} onChange={(positiveCriteria) => onChange({ ...signal, positiveCriteria })} /></div><details className="mt-4 rounded-lg border border-[#E5E0D8] bg-[#FAF8F4] px-4 py-3"><summary className="cursor-pointer text-sm font-semibold text-[#5C5852]">Advanced settings</summary><div className="mt-4 grid gap-4 md:grid-cols-3">{negative && <label className="text-xs font-semibold text-[#4C4944]">Effect<select className={input} value={signal.effect} onChange={(event) => onChange({ ...signal, effect: event.target.value as SignalEffect })}><option value="penalty">Lower priority</option><option value="disqualifier">Exclude company</option></select></label>}<label className="text-xs font-semibold text-[#4C4944]">Importance<select className={input} value={signal.weight >= 15 ? 20 : signal.weight >= 8 ? 10 : 5} onChange={(event) => onChange({ ...signal, weight: Number(event.target.value) })}>{importance.map((item) => <option key={item.label} value={item.value}>{item.label}</option>)}</select></label><label className="text-xs font-semibold text-[#4C4944]">Evidence age<select className={input} value={signal.freshnessWindowDays <= 180 ? 180 : signal.freshnessWindowDays <= 365 ? 365 : 730} onChange={(event) => onChange({ ...signal, freshnessWindowDays: Number(event.target.value) })}>{ages.map((item) => <option key={item.label} value={item.value}>{item.label}</option>)}</select></label></div></details></article>
}

function ProfileSummary({ profile }: { profile: ProfileDraft }) {
  const positives = profile.signals.filter((item) => item.effect === 'positive'); const warnings = profile.signals.filter((item) => item.effect !== 'positive')
  const checks = [{ label: 'Service selected', done: Boolean(profile.serviceRole && profile.description) }, { label: 'Target audience defined', done: Boolean(profile.industries || profile.geographies || profile.companySize) }, { label: 'Buying signal added', done: positives.some((item) => item.question && item.positiveCriteria) }]
  return <aside className="h-fit rounded-2xl bg-[#1D1B19] p-5 text-white lg:sticky lg:top-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#FFA56F]">Live profile</p><h2 className="mt-3 text-lg font-semibold">{profile.name || 'Untitled profile'}</h2><p className="mt-3 text-sm leading-6 text-[#D9D3CB]">We’ll look for <strong className="text-white">{profile.companySize || 'companies of any size'}</strong>{profile.industries && <> in <strong className="text-white">{profile.industries}</strong></>}{profile.geographies && <> across <strong className="text-white">{profile.geographies}</strong></>}.</p><div className="mt-5 grid grid-cols-2 gap-2"><div className="rounded-xl bg-white/10 p-3"><strong className="text-xl text-[#FF7A2F]">{positives.length}</strong><span className="mt-1 block text-xs text-[#CFC8C0]">buying signals</span></div><div className="rounded-xl bg-white/10 p-3"><strong className="text-xl text-[#FFBE98]">{warnings.length}</strong><span className="mt-1 block text-xs text-[#CFC8C0]">warnings</span></div></div><div className="mt-5 border-t border-white/15 pt-5"><p className="text-xs font-bold uppercase tracking-wider text-[#CFC8C0]">Ready to discover</p><ul className="mt-3 space-y-2">{checks.map((check) => <li className="flex items-center gap-2 text-sm" key={check.label}><span className={`grid size-5 place-items-center rounded-full text-xs ${check.done ? 'bg-[#E86722] text-white' : 'bg-white/10 text-[#9D9790]'}`}>{check.done ? '✓' : '·'}</span><span className={check.done ? 'text-white' : 'text-[#9D9790]'}>{check.label}</span></li>)}</ul></div></aside>
}

export function ProfileWorkspace({ onReady }: { onReady?: () => void }) {
  const [profile, setProfile] = useState<ProfileDraft | null>(null); const [step, setStep] = useState(0); const [furthestStep, setFurthestStep] = useState(0); const [state, setState] = useState<'loading' | 'ready' | 'saving' | 'saved'>('loading'); const [loadError, setLoadError] = useState(''); const [saveError, setSaveError] = useState('')
  useEffect(() => { void getProfile().then((value) => { setProfile(value); setState('ready') }).catch((error) => { setLoadError(errorMessage(error)); setState('ready') }) }, [])
  const groups = useMemo(() => ({ buying: profile?.signals.filter((item) => item.effect === 'positive') ?? [], negative: profile?.signals.filter((item) => item.effect !== 'positive') ?? [] }), [profile])
  if (state === 'loading') return <div className="rounded-xl border border-[#DED9D1] bg-white p-10 text-[#73706A]">Loading service profile…</div>
  if (!profile) return <div className="rounded-xl border border-[#E6B8AE] bg-[#FFF4F1] p-10 text-[#8A2F20]"><p>The service profile could not be loaded.</p>{loadError && <p className="mt-2 text-sm">{loadError}</p>}</div>
  const chooseService = (name: string) => { const service = serviceOptions.find((item) => item.name === name); if (service) setProfile({ ...profile, name: service.profileName, serviceRole: service.name, description: service.description }) }
  const replace = (next: SignalDraft) => setProfile({ ...profile, signals: profile.signals.map((item) => item.id === next.id ? next : item) }); const remove = (id: string) => setProfile({ ...profile, signals: profile.signals.filter((item) => item.id !== id) }); const add = (effect: SignalEffect) => setProfile({ ...profile, signals: [...profile.signals, { id: crypto.randomUUID(), question: '', positiveCriteria: '', exclusions: '', effect, weight: effect === 'positive' ? 20 : 10, freshnessWindowDays: 365 }] })
  const serviceSelected = serviceOptions.some((item) => item.name === profile.serviceRole)
  const continueStep = () => { if (step === 0 && !serviceSelected) return; setState('ready'); setStep((value) => { const next = value + 1; setFurthestStep((furthest) => Math.max(furthest, next)); return next }) }
  const persist = async () => { setState('saving'); setSaveError(''); try { setProfile(await saveProfile(profile)); setState('saved'); onReady?.() } catch (error) { setSaveError(errorMessage(error)); setState('ready') } }
  return <div className="text-[#20242A]"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-wider text-[#A44818]">Service profile · Version {profile.version ?? 1}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Tell us what a good opportunity looks like</h1><p className="mt-3 text-sm leading-6 text-[#68645F]">Set your target once. Discovery and research will use it to find and rank relevant companies.</p></div><ol className="mt-8 grid max-w-4xl gap-2 md:grid-cols-3">{steps.map((label, index) => <li key={label}><button aria-current={step === index ? 'step' : undefined} className={`flex w-full items-center gap-3 rounded-xl border px-4 py-3 text-left text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-45 ${step === index ? 'border-[#E86722] bg-[#FFF1E8] text-[#9F3E0E]' : 'border-[#E2DED7] bg-white text-[#716C65]'}`} disabled={index > furthestStep} onClick={() => setStep(index)}><span className={`grid size-6 place-items-center rounded-full text-xs ${step === index ? 'bg-[#C94F12] text-white' : index < step ? 'bg-[#3F7054] text-white' : 'bg-[#E5E1DA]'}`}>{index < step ? '✓' : index + 1}</span>{label}</button></li>)}</ol><div className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1fr)_19rem]"><section className="rounded-2xl border border-[#DCD7CF] bg-[#FCFBF8] p-6 shadow-[0_8px_28px_rgba(58,45,31,0.06)] sm:p-8">
    {step === 0 && <div><h2 className="text-xl font-semibold">Choose your service</h2><p className="mt-2 text-sm text-[#6F6A64]">Start with a template. You can edit the wording before saving.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{serviceOptions.map((service) => { const active = profile.serviceRole === service.name; return <button aria-pressed={active} className={`rounded-xl border p-4 text-left transition ${active ? 'border-[#E86722] bg-[#FFF0E6] shadow-sm' : 'border-[#D9D3CA] bg-white hover:border-[#E86722]'}`} key={service.name} onClick={() => chooseService(service.name)} type="button"><span className="flex items-start justify-between gap-2"><strong className="text-sm">{service.title}</strong><span className={`grid size-5 place-items-center rounded-full border text-xs ${active ? 'border-[#D85A17] bg-[#D85A17] text-white' : 'border-[#BDB6AD]'}`}>{active ? '✓' : ''}</span></span><span className="mt-2 block text-xs leading-5 text-[#6F6A64]">{service.short}</span></button> })}</div><div className="mt-6"><Field help="Internal context used by research and message generation." label="How we help" multiline value={profile.description} onChange={(description) => setProfile({ ...profile, description })} /></div></div>}
    {step === 1 && <div><h2 className="text-xl font-semibold">Define your ideal customer</h2><p className="mt-2 text-sm text-[#6F6A64]">Select more than one option, or leave a group empty to keep discovery broad.</p><div className="mt-6 space-y-7"><ChipGroup help="Choose the sectors where your offer is most relevant." label="Industries" onToggle={(value) => setProfile({ ...profile, industries: toggleValue(profile.industries, value) })} options={industries} selected={profile.industries} /><ChipGroup help="Discovery supports other markets too; Worldwide removes the regional preference." label="Regions" onToggle={(value) => setProfile({ ...profile, geographies: toggleValue(profile.geographies, value) })} options={regions} selected={profile.geographies} /><label className="block text-sm font-semibold text-[#353A40]">Company size<span className="mt-1 block text-xs font-normal leading-5 text-[#73706A]">Unknown headcount remains eligible with lower confidence.</span><select className={input} value={profile.companySize} onChange={(event) => setProfile({ ...profile, companySize: event.target.value })}><option value="">Any company size</option><option value="1,000+ employees">1,000+ employees</option><option value="5,000+ employees">5,000+ employees</option><option value="10,000+ employees">10,000+ employees</option></select></label><Field help="Optional traits that make delivery valuable." label="Operational characteristics" multiline placeholder="Multiple sites, shared services, high-volume repetitive processes…" value={profile.operationalComplexity} onChange={(operationalComplexity) => setProfile({ ...profile, operationalComplexity })} /></div></div>}
    {step === 2 && <div><h2 className="text-xl font-semibold">Choose what research should notice</h2><p className="mt-2 text-sm text-[#6F6A64]">Strong, concrete signals increase priority. Warnings lower it or exclude a poor fit.</p><div className="mt-7 flex items-center justify-between gap-4"><div><h3 className="font-semibold">Buying signals</h3><p className="mt-1 text-xs text-[#73706A]">Evidence of active need, change, or investment.</p></div><button className="rounded-lg bg-[#C94F12] px-4 py-2.5 text-sm font-semibold text-white" onClick={() => add('positive')} type="button">Add signal</button></div><div className="mt-4 space-y-4">{groups.buying.map((item, index) => <SignalCard index={index} key={item.id} onChange={replace} onRemove={() => remove(item.id)} signal={item} />)}{!groups.buying.length && <p className="rounded-xl border border-dashed border-[#CFC8BE] bg-white p-6 text-center text-sm text-[#68645F]">Add at least one signal to help rank companies.</p>}</div><div className="mt-8 flex items-center justify-between gap-4 border-t border-[#E3DED6] pt-7"><div><h3 className="font-semibold">Warnings and exclusions</h3><p className="mt-1 text-xs text-[#73706A]">Optional reasons why a company may be a weaker fit.</p></div><button className="rounded-lg border border-[#D55A1C] bg-white px-4 py-2.5 text-sm font-semibold text-[#B44712]" onClick={() => add('penalty')} type="button">Add warning</button></div><div className="mt-4 space-y-4">{groups.negative.map((item, index) => <SignalCard index={index} key={item.id} negative onChange={replace} onRemove={() => remove(item.id)} signal={item} />)}</div></div>}
    {saveError && <div className="mt-6 rounded-xl border border-[#E6B8AE] bg-[#FFF4F1] p-4 text-sm text-[#8A2F20]" role="alert"><p className="font-semibold">The profile could not be saved.</p><p className="mt-1">{saveError}</p><p className="mt-1 text-xs">Your changes are still here. Review them and try again.</p></div>}
    <div className="mt-8 flex items-center justify-between border-t border-[#E3DED6] pt-5"><button className="rounded-lg border border-[#D5D0C8] bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-40" disabled={step === 0} onClick={() => setStep((value) => value - 1)}>Back</button><div className="flex items-center gap-3">{step === 0 && !serviceSelected && <span className="hidden text-xs font-medium text-[#8A4030] sm:block">Select a service to continue.</span>}{state === 'saved' && <span className="text-sm font-medium text-[#31704E]">Profile saved</span>}{step < 2 ? <button className="rounded-lg bg-[#C94F12] px-5 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:bg-[#C9C2BA]" disabled={step === 0 && !serviceSelected} onClick={continueStep}>Continue</button> : <button className="rounded-lg bg-[#C94F12] px-5 py-2.5 text-sm font-semibold text-white" disabled={state === 'saving'} onClick={() => void persist()}>{state === 'saving' ? 'Saving…' : 'Save profile and discover companies'}</button>}</div></div>
  </section><ProfileSummary profile={profile} /></div></div>
}
